# Generated by Django 3.0.1 on 2020-01-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('post_images', models.ImageField(default='default.jpg', upload_to='post_images')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
