# Generated by Django 3.0.1 on 2020-01-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='date',
            new_name='post_date',
        ),
    ]
