# Generated by Django 3.0.1 on 2020-02-10 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_react_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_images',
            field=models.ImageField(default='post_images/default.jpg', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='react',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 13, 23, 20, 721655)),
        ),
    ]
